### ISSUE TITLE
Conflict with Lazysizes.js

### ISSUE THREAD

**Issue by jzelaya-manduka** [shubhamjain/svg-loader#2] opened 2021-05-27 19:56 UTC
When using with Lazysizes.js, the SVG attributes are added to an img tag as soon as it's lazyloaded on the page. This causes the image to appear skewed.
![Screen Shot 2021-05-27 at 12 41 43 PM](https://user-images.githubusercontent.com/67347164/119889042-f8c1b080-beea-11eb-8a78-93927decd962.png)

**Comment by shubhamjain** [comment] 2021-05-28 07:30
It shouldn't happen as the selector is `svg[data-src]` but it seems there's some conflict that happens. I will fix it this weekend.

**Comment by shubhamjain** [comment] 2021-05-30 15:44
I am not able to reproduce this issue. Can you please link to a sample page where this might be happening?

**Comment by shubhamjain** [comment] 2021-11-17 07:45
Closing as there's not enough to debug the issue.

**Closed as completed by shubhamjain** 2021-11-17 07:45 UTC
